### ISSUE TITLE
后勤方案组合排序卡住

### ISSUE THREAD

**Issue by Neight99** [CHANTXU64/Girls-Frontline#2]
在后勤方案组合模式里，添加完后勤方案之后点击开始后勤方案组合排序，网页就卡死了。
我一开始还以为是本地计算要时间，结果去吃了个饭回来发现直接用了100+G虚拟内存，而且网页还是卡住的。
是我使用方法不对还是有bug啊orz

**Comment by Neight99** [comment]
而且cpu这段时间也一直是单线程满载，大概二十分钟吧。

**Comment by CHANTXU64** [comment]
你好，能否将你的全局数据导出并发出来？

**Comment by Neight99** [comment]
直接卡死的话，我是强制终止掉再导出？还是咋办orz

**Comment by CHANTXU64** [comment]
直接关掉浏览器标签页再重新打开网页就行（你没有禁用cookies），如果没有出现强制清除Web存储的警告数据都还在。你先导出数据，再看看能否重现这个bug。一般来说，在后勤方案组合模式下，视CPU性能平均一个后勤方案排序时间为0.6s~2s，也就是说10个后勤排序时间应该也不会超过半分钟，如果等待时间太长，应该是又出bug了，可能是某个循环没有跳出。

**Comment by Neight99** [comment]
导出的全局数据内容：
N4IgJghgLhIFygG4FMBOBnAlgewHbxAEYA6AJmIAYBaVAY1JABoQAVCAIwDkIBbZAgIK4AnlEx8mIABLYArqgA2wgPKoW2GAoLrNktuyGjxyAMKz0UbD3gBtAOykKjAKwBdZvpbGY7BafOW1nA2AMwUTjau7iAA4qjI0ADKsrS0yOjoAErQ/HDOAJzMAJLoAPpxCVDJqelZOQCqAA7wAGYQCujIzCYAFhCNUGgAMuKYUPCEpN14UKgQtFAA6siYAOY943lOrBCoq8hQAGrtsrk2TheMl9fRiRAoYLbRAAoKELgmVuyYuNA4+AhwDl4KALLtNiBHI4qBQACxUUj5STIXCPOCQijQijOKhhEAAX2YtHk8VwmxsjgAbKQQiFGKRYYQQvlKfTKXZnJTWYQ7BQOZdKSE7C5CIUKNEYHsDrYwuFwoxZXKFXL5Y4VVdGIQlVr5eLmGBkDx3mibPkheyXAAOSlwhUMkKw+n5UjOS4hQWMWGWwhXaJDbCrTAWTC0dAAEWgsEBYNQUAjgwIUOocIRSOYKLA8dyGKxOLxzEsmgjwnQ8BCPpAhfaXj4zzQxdsDkuTcYLbbjlbHZbTnbPa7/b7zYHncHI7Ho97Y8ng+ijTeuFLwVAYlraBwJvOmvcFMYlu3hUIbkYNkIrNIpG3NKd27CCsIUWY6HuyDRoF+EnRKcRAD8U7eAATYjChC/jifKMIBYGWqBVCEI6kGwc4MGkD6CHnshloQUBP5AfmsSJNkCZ5IUIBBqU9TPK07SdN0fQDGgExTDsXC8NmhgrvwHgcGYFhWI2HZHiAACyQZYHgi6RI+kpQDWuQUISlbGPALYgLgsg8OwDFwNs8RCGAtDYLY1wasZ4r4rO87oJw6maagEwKZ8C7qQM/zxlGoLSVmiaYsm8KIsiqJeeiSYwmBlKSFWCjFouwogHO7wAGJvKsRkmWlFwWe8EmZQu1kaVp8nMH4KBaHAhCiviCmJFIAiEAQhAQJSzhgHYlL5JM5Z2GkXKEJa+TOM4dgQChsLsIyyDsJSyAUBAFDIGaBJAA===

**Comment by CHANTXU64** [comment]
谢谢，现在bug已修复，很快会发布新版本
